services:
  home-assistant:
    container_name: home-assistant-2024.11.3
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /config
      - ./configuration.yaml:/config/configuration.yaml
      - ../../custom_components/uhppoted:/config/custom_components/uhppoted
    restart: no
    privileged: false
    network_mode: "bridge"
    ports:
       - "8123:8123"

