services:
  home-assistant:
    container_name: home-assistant-stable
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /config
      - ./configuration.yaml:/config/configuration.yaml
      - ../../../custom_components/uhppoted:/config/custom_components/uhppoted
      - ../../../../uhppoted-lib-python:/usr/local/lib/uhppoted
    restart: no
    privileged: false
    network_mode: "bridge"
    ports:
       - "8123:8123"
       - "60001:60001/udp"

