# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# automation: !include automations.yaml
# script: !include scripts.yaml
# scene: !include scenes.yaml

logger:
  default: info
  logs:
    homeassistant.components.cloud: debug

uhppoted:
    bind_address: 192.168.1.100
    broadcast_address: 192.168.1.255:60000
    listen_address: 192.168.1.100:60001
    debug: false
    timezone: CEST
    timeout: 2.5
    max_cards: 7
    preferred_cards:
        - 8165535
        - 8165536
        - 8165537
        - 8165536
        - 8165535
    card_PINs: true
    controllers_poll_interval: 29
    doors_poll_interval: 31
    cards_poll_interval: 33
    events_poll_interval: 35
    controllers:
        - 
            controller: 504030201
            address: 192.168.1.100
            port: 54321
            protocol: UDP
        - 
            controller: 605040302
            address: 192.168.1.100
            port: 54321
            protocol: UDP
        - 
            controller: 706050403
            address: 192.168.1.100
            port: 54321
            timeout: 0.56
            protocol: TCP

