name: alpha

on:
  workflow_dispatch:

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: ^3.11
      id: python

    - name: Install Python packages
      run: pip install toml yapf

    - name: Check out code
      uses: actions/checkout@v4

    - name: Build
      run: make build-all
