name: debug

on:
  workflow_dispatch:

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: ^3.11
      id: python

    - name: Install Python packages
      run: pip install toml yapf pytest pytest-homeassistant-custom-component uhppoted netifaces

    - name: Check out code
      uses: actions/checkout@v4

    - name: Unit tests
      run: python3 -m unittest tests/uhppoted/*.py 
